# Generated by Django 5.0.6 on 2024-06-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("workout_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("created_ts", models.DateTimeField(auto_now=True)),
                ("sets", models.IntegerField()),
                ("reps", models.IntegerField()),
            ],
            options={
                "db_table": "workouts",
                "ordering": ["workout_id"],
            },
        ),
    ]
